PORTNAME=	gr
DISTVERSION=	0.73.6
CATEGORIES=	math

MAINTAINER=	y@trombik.org
COMMENT=	GR framework: a graphics library for visualisation applications

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.md

USES=	gmake qt:5

USE_QT=	core gui widgets
USE_GITHUB=	yes
GH_TUPLE=	sciapp:gr:v${DISTVERSION}

.include <bsd.port.mk>
